# Generated by Django 4.1.1 on 2022-11-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('CPF', models.IntegerField()),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('formacao', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('experiencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Palestras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palestra', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('hora', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
